networks:
  appnet:
    driver: bridge

volumes:
  db-data:

services:
  web:
    image: nginx:latest
    # ports: 
    #   - "8080:80" # не зрозумів чому при масштабуванні отримую помилку що порт вже зайнятий
    volumes:
      - ./web-app:/usr/share/nginx/html:ro
    networks:
      - appnet

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - appnet

  cache:
    image: redis:latest
    networks:
      - appnet
